In [41]:
#https://en.wikipedia.org/wiki/Iris_flower_data_set
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

In [42]:
iris = load_iris()

In [43]:
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[ 5.1  3.5  1.4  0.2]
0


In [44]:
test_idx = [0,50,100]

In [45]:
#traning data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [46]:
#testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [47]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [48]:
print(test_target)
print(clf.predict(test_data))

[0 1 2]
[0 1 2]


In [49]:
with open("iris.dot", 'w') as f:
    f = tree.export_graphviz(clf, out_file=f)

In [50]:
print(test_data[1], test_target[1])
print(iris.feature_names, iris.target_names)

[ 7.   3.2  4.7  1.4] 1
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
